print("Programmer: Lanz Andrei Molina")
print("Date Created: July 6, 2023")
print("Description of the Program: This is my first project in github.")
print()
print("First Name: Lanz Andrei")
print("Middle Name: Tanedo")
print("Last Name: Molina")
print("Course: BS Information Technology")
print("Year: 3rd year")
print("Gender: Male")
print("Civil Status: Single")
print("Nationality: Filipino")
print()
print("Motto: Actions speak louder than words.")
print("PHINMA Araullo University")
print("College: CITE")
